# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  languageName: English
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  languageName: 中文 (简体)
  title: 许煜
  params:
    description: 许煜的个人学术主页
  menu:
    main:
      - name: 主页
        url: '#about'
        weight: 10
      - name: 特色论文
        url: '#featured'
        weight: 20
      - name: 发表论文
        url: '#publications'
        weight: 30
      - name: 学术职位
        url: '#positions'
        weight: 40
      - name: 学术活动
        url: '#academic'
        weight: 50
      - name: 教学
        url: '#teaching'
        weight: 60
      - name: 联系方式
        url: '#contact'
        weight: 70
